# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-17 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import tweet.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweet.validators.validate_content]),
        ),
    ]
